#!/usr/bin/env bash
#
# Dispatch appliance — first-boot setup. Runs once (via dispatch-firstboot.service) before the Dispatch
# service: it gives this VM its own unique SQL Server SA password, configures + starts SQL Server Express,
# substitutes that password into the Dispatch connection string (a placeholder is baked into the image), and
# lets systemd start Dispatch (ordered After= this unit). The Dispatch service then creates the DispatchLog
# database and schema on first start. OS-level secrets (SSH host keys, machine-id) are regenerated by
# cloud-init / systemd; the at-rest encryption key (.dispatch-key) and dashboard TLS cert are generated by
# the service itself on first start — none of those are baked into the image, so every appliance is unique.
#
set -euo pipefail

MARKER="/var/lib/dispatch/.appliance-firstboot-done"
APPSETTINGS="/var/lib/dispatch/appsettings.json"
SQLCMD="/opt/mssql-tools18/bin/sqlcmd"

[ -e "$MARKER" ] && { echo "dispatch-firstboot: already done"; exit 0; }
log() { echo "dispatch-firstboot: $*"; }
set -x   # trace each step to the console so a first-boot failure is diagnosable

# 1. Unique SA password. Alnum + a fixed complexity suffix → meets SQL's policy and contains no characters
#    that are special to the shell, sed, or JSON, so the substitution below is safe.
SA_PW="$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 28)Aa1!"

# 2. Configure SQL Server Express (EULA accepted) with that password, then enable + start it.
log "configuring SQL Server Express"
MSSQL_SA_PASSWORD="$SA_PW" MSSQL_PID="Express" ACCEPT_EULA="Y" /opt/mssql/bin/mssql-conf -n setup
systemctl enable --now mssql-server

# 3. Wait for SQL to accept logins before pointing Dispatch at it.
log "waiting for SQL Server"
ready=0
for _ in $(seq 1 60); do
  if "$SQLCMD" -S localhost -U sa -P "$SA_PW" -C -No -Q "SELECT 1" >/dev/null 2>&1; then ready=1; break; fi
  sleep 2
done
[ "$ready" = 1 ] || { log "ERROR: SQL Server did not become ready"; exit 1; }

# 4. Inject the generated SA password into the connection string (the image ships a __SA_PASSWORD__ placeholder).
log "finalizing the Dispatch connection string"
sed -i "s|__SA_PASSWORD__|${SA_PW}|" "$APPSETTINGS"
chown dispatch:dispatch "$APPSETTINGS"
chmod 600 "$APPSETTINGS"

# 5. Done. systemd starts dispatch.service next (it is ordered After=/Requires= this unit).
touch "$MARKER"
log "first-boot complete"
