#!/usr/bin/env bash
#
# Dispatch appliance - first-boot setup. Runs once (via dispatch-firstboot.service) before the Dispatch
# service: it gives this VM its own unique PostgreSQL password, creates the dispatch role + DispatchLog
# database, starts PostgreSQL, substitutes that password into the Dispatch connection string (a placeholder
# is baked into the image), and lets systemd start Dispatch (ordered After= this unit). The Dispatch service
# then creates the DispatchLog schema on first start. OS-level secrets (SSH host keys, machine-id) are
# regenerated by cloud-init / systemd; the at-rest encryption key (.dispatch-key) and dashboard TLS cert are
# generated by the service itself on first start - none of those are baked into the image, so every appliance
# is unique.
#
set -euo pipefail

MARKER="/var/lib/dispatch/.appliance-firstboot-done"
APPSETTINGS="/var/lib/dispatch/appsettings.json"

[ -e "$MARKER" ] && { echo "dispatch-firstboot: already done"; exit 0; }
log() { echo "dispatch-firstboot: $*"; }

# 1. Unique database password. Alnum (from a FINITE source so nothing gets SIGPIPE'd under pipefail) + a fixed
#    complexity suffix, containing no characters special to the shell, sed, JSON, or a SQL string literal.
DB_PW="$(openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | cut -c1-28)Aa1x"

# 2. Ensure the default cluster is initialized + started, then enable + start PostgreSQL. The Debian
#    postgresql package creates a default "main" cluster on install; start it via the systemd unit.
log "configuring PostgreSQL"
systemctl enable --now postgresql

# 3. Wait for PostgreSQL to accept connections before creating the role/database.
log "waiting for PostgreSQL"
ready=0
for _ in $(seq 1 60); do
  if pg_isready -h localhost -p 5432 >/dev/null 2>&1; then ready=1; break; fi
  sleep 2
done
[ "$ready" = 1 ] || { log "ERROR: PostgreSQL did not become ready"; exit 1; }

# 4. Create the dispatch role (with the generated password) and the DispatchLog database it owns. Idempotent
#    so a re-run before the marker is written does not fail on an already-created role/database.
log "creating the dispatch role and DispatchLog database"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'dispatch') THEN
    CREATE ROLE dispatch LOGIN PASSWORD '${DB_PW}';
  ELSE
    ALTER ROLE dispatch LOGIN PASSWORD '${DB_PW}';
  END IF;
END
\$\$;
SELECT 'CREATE DATABASE "DispatchLog" OWNER dispatch'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'DispatchLog')\gexec
SQL

# 5. Inject the generated password into the connection string (the image ships a __DB_PASSWORD__ placeholder).
log "finalizing the Dispatch connection string"
sed -i "s|__DB_PASSWORD__|${DB_PW}|" "$APPSETTINGS"
chown dispatch:dispatch "$APPSETTINGS"
chmod 600 "$APPSETTINGS"

# 5. Done. systemd starts dispatch.service next (it is ordered After=/Requires= this unit).
touch "$MARKER"
log "first-boot complete"
