-- Dispatch schema v1, SQLite translation of Migrations/Postgres/0001_init.sql (spec §6.11, §7.6, §12.3).
-- Runs as a single batch; tables are created in FK-dependency order. Guarded by schema_version.
--
-- Translation notes, and the reasoning behind each:
--   * GENERATED BY DEFAULT AS IDENTITY -> INTEGER PRIMARY KEY AUTOINCREMENT. AUTOINCREMENT (not bare
--     INTEGER PRIMARY KEY) is deliberate: without it SQLite reuses the ids of deleted rows, and relay_log
--     ids are handed out to the keyset cursor and to purge/archive batches. Reused ids would let a cursor
--     silently skip or repeat rows after a purge.
--   * timestamptz -> TEXT holding ISO-8601 UTC. See SqliteDialect for the format contract.
--   * boolean     -> INTEGER 0/1, DEFAULT false -> DEFAULT 0. SQLite accepts the column in a WHERE clause
--                    as a truth value, so the partial indexes below still work.
--   * varchar(n)  -> TEXT. SQLite does not enforce length; the repositories already truncate in C#
--                    (SqlLogRepository.Trunc), so enforcement was never coming from the database.
--   * INCLUDE (...) covering indexes are dropped -- SQLite has no such thing. The leading key columns are
--     preserved, so these stay index seeks; they cost one extra row lookup per matched row instead of
--     being fully covering. Performance difference, not a correctness one.
--   * date -> TEXT 'YYYY-MM-DD', matching CURRENT_DATE's output. Bind via ISqlDialect.DateParam.

CREATE TABLE config (
    "key"      TEXT    NOT NULL PRIMARY KEY,
    value      TEXT    NOT NULL,
    encrypted  INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE relays (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    name              TEXT    NOT NULL UNIQUE,
    provider          TEXT    NOT NULL,
    is_default        INTEGER NOT NULL DEFAULT 0,
    enabled           INTEGER NOT NULL DEFAULT 1,
    max_concurrency   INTEGER NOT NULL DEFAULT 4,
    max_message_bytes INTEGER NOT NULL DEFAULT 0,
    created_at        TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IX_relays_default ON relays (is_default) WHERE is_default;

CREATE TABLE routing_rules (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    priority          INTEGER NOT NULL UNIQUE,
    name              TEXT    NOT NULL,
    recipient_pattern TEXT    NULL,
    sender_pattern    TEXT    NULL,
    relay_id          INTEGER NOT NULL REFERENCES relays(id),
    enabled           INTEGER NOT NULL DEFAULT 1,
    created_at        TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE api_keys (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    key_id                TEXT    NOT NULL UNIQUE,
    key_hash              TEXT    NOT NULL,
    name                  TEXT    NOT NULL,
    created_at            TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at          TEXT    NULL,
    message_count         INTEGER NOT NULL DEFAULT 0,
    revoked               INTEGER NOT NULL DEFAULT 0,
    revoked_at            TEXT    NULL,
    rate_limit_per_minute INTEGER NOT NULL DEFAULT 100,
    scope                 TEXT    NOT NULL DEFAULT 'send'
);
CREATE INDEX IX_api_keys_key_id ON api_keys (key_id) WHERE NOT revoked;

CREATE TABLE relay_counters (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    date      TEXT    NOT NULL,
    relay_id  INTEGER NOT NULL REFERENCES relays(id),
    received  INTEGER NOT NULL DEFAULT 0,
    delivered INTEGER NOT NULL DEFAULT 0,
    failed    INTEGER NOT NULL DEFAULT 0,
    retried   INTEGER NOT NULL DEFAULT 0,
    denied    INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT UQ_relay_counters UNIQUE (date, relay_id)
);
CREATE INDEX IX_relay_counters_date ON relay_counters (date DESC);

CREATE TABLE relay_log (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    logged_at           TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    spool_id            TEXT    NOT NULL,
    event               TEXT    NOT NULL,
    status              TEXT    NOT NULL,
    retry_attempt       INTEGER NOT NULL DEFAULT 0,
    from_address        TEXT    NOT NULL,
    from_domain         TEXT    NOT NULL,
    to_addresses        TEXT    NOT NULL,
    to_domain           TEXT    NOT NULL,
    subject             TEXT    NOT NULL,
    size_bytes          INTEGER NOT NULL DEFAULT 0,
    relay_id            INTEGER NULL REFERENCES relays(id),
    relay_name          TEXT    NULL,
    routing_rule_id     INTEGER NULL REFERENCES routing_rules(id),
    routing_rule_name   TEXT    NULL,
    routing_matched     INTEGER NOT NULL DEFAULT 0,
    provider            TEXT    NULL,
    provider_message_id TEXT    NULL,
    provider_response   TEXT    NULL,
    duration_ms         INTEGER NULL,
    error               TEXT    NULL,
    ingest_source       TEXT    NOT NULL DEFAULT 'SMTP',
    source_ip           TEXT    NULL,
    api_key_id          INTEGER NULL REFERENCES api_keys(id),
    api_key_name        TEXT    NULL,
    tags                TEXT    NULL
);
CREATE INDEX IX_relay_log_status_date ON relay_log (status, logged_at DESC);
CREATE INDEX IX_relay_log_from_domain ON relay_log (from_domain, logged_at DESC);
CREATE INDEX IX_relay_log_to_domain   ON relay_log (to_domain, logged_at DESC);
CREATE INDEX IX_relay_log_source      ON relay_log (ingest_source, logged_at DESC);
CREATE INDEX IX_relay_log_purge       ON relay_log (logged_at);

CREATE TABLE config_smtp_credentials (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    username      TEXT    NOT NULL UNIQUE,
    password_hash TEXT    NOT NULL,
    created_at    TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at  TEXT    NULL
);

-- Seed a single default relay in the "Unconfigured" state: until an administrator picks a provider,
-- Dispatch refuses to relay (mail is never silently delivered or discarded).
INSERT INTO relays (name, provider, is_default, enabled, max_concurrency)
VALUES ('default', 'Unconfigured', 1, 1, 4);
