// <auto-generated />
using System;
using Dispatch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dispatch.Data.Sqlite.Migrations
{
    [DbContext(typeof(DispatchDbContext))]
    [Migration("20260719185428_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("Dispatch.Data.ApiKeyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_id");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<long>("MessageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("message_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("RateLimitPerMinute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(100)
                        .HasColumnName("rate_limit_per_minute");

                    b.Property<bool>("Revoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("revoked");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("send")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "KeyId" }, "IX_api_keys_key_id")
                        .HasFilter("NOT revoked");

                    b.HasIndex(new[] { "KeyId" }, "UQ_api_keys_key_id")
                        .IsUnique();

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Dispatch.Data.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("event");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<DateTime>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("logged_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Info")
                        .HasColumnName("severity");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_ip");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "LoggedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_audit_log_kind");

                    b.HasIndex("LoggedAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("IX_audit_log_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Dispatch.Data.ConfigEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<bool>("Encrypted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("encrypted");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("config", (string)null);
                });

            modelBuilder.Entity("Dispatch.Data.RelayCounterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<long>("Delivered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("delivered");

                    b.Property<long>("Denied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("denied");

                    b.Property<long>("Failed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("failed");

                    b.Property<long>("Received")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("received");

                    b.Property<int>("RelayId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("relay_id");

                    b.Property<long>("Retried")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("retried");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsDescending()
                        .HasDatabaseName("IX_relay_counters_date");

                    b.HasIndex("Date", "RelayId")
                        .IsUnique()
                        .HasDatabaseName("UQ_relay_counters");

                    b.ToTable("relay_counters", (string)null);
                });

            modelBuilder.Entity("Dispatch.Data.RelayEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<int>("MaxConcurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(4)
                        .HasColumnName("max_concurrency");

                    b.Property<int>("MaxMessageBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("max_message_bytes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("IX_relays_default")
                        .HasFilter("is_default");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("relays", (string)null);
                });

            modelBuilder.Entity("Dispatch.Data.RelayLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ApiKeyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("api_key_id");

                    b.Property<string>("ApiKeyName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key_name");

                    b.Property<int>("AttachmentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("attachment_count");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("event");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("from_address");

                    b.Property<string>("FromDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("from_domain");

                    b.Property<string>("IngestSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("SMTP")
                        .HasColumnName("ingest_source");

                    b.Property<DateTime>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("logged_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_message_id");

                    b.Property<string>("ProviderResponse")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_response");

                    b.Property<int?>("RelayId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("relay_id");

                    b.Property<string>("RelayName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("relay_name");

                    b.Property<int>("RetryAttempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_attempt");

                    b.Property<bool>("RoutingMatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("routing_matched");

                    b.Property<int?>("RoutingRuleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("routing_rule_id");

                    b.Property<string>("RoutingRuleName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("routing_rule_name");

                    b.Property<int>("SizeBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("size_bytes");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_ip");

                    b.Property<string>("SpoolId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("spool_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("ToAddresses")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("to_addresses");

                    b.Property<string>("ToDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("to_domain");

                    b.Property<string>("XMailer")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("x_mailer");

                    b.HasKey("Id");

                    b.HasIndex("LoggedAt")
                        .HasDatabaseName("IX_relay_log_purge");

                    b.HasIndex("ApiKeyId", "LoggedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_relay_log_api_key")
                        .HasFilter("api_key_id IS NOT NULL");

                    b.HasIndex("FromDomain", "LoggedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_relay_log_from_domain");

                    b.HasIndex("IngestSource", "LoggedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_relay_log_source");

                    b.HasIndex("RelayId", "LoggedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_relay_log_relay");

                    b.HasIndex("RoutingRuleId", "LoggedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_relay_log_rule");

                    b.HasIndex("Status", "LoggedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_relay_log_status_date");

                    b.HasIndex("ToDomain", "LoggedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_relay_log_to_domain");

                    b.HasIndex("SpoolId", "LoggedAt", "Id")
                        .HasDatabaseName("IX_relay_log_spool_id");

                    b.ToTable("relay_log", (string)null);
                });

            modelBuilder.Entity("Dispatch.Data.RoutingRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("RecipientPattern")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("recipient_pattern");

                    b.Property<int>("RelayId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("relay_id");

                    b.Property<string>("SenderPattern")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_pattern");

                    b.HasKey("Id");

                    b.HasIndex("Priority")
                        .IsUnique();

                    b.HasIndex("RelayId");

                    b.ToTable("routing_rules", (string)null);
                });

            modelBuilder.Entity("Dispatch.Data.SmtpCredentialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("config_smtp_credentials", (string)null);
                });

            modelBuilder.Entity("Dispatch.Data.RelayLogEntity", b =>
                {
                    b.HasOne("Dispatch.Data.ApiKeyEntity", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId");

                    b.HasOne("Dispatch.Data.RelayEntity", null)
                        .WithMany()
                        .HasForeignKey("RelayId");

                    b.HasOne("Dispatch.Data.RoutingRuleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoutingRuleId");
                });

            modelBuilder.Entity("Dispatch.Data.RoutingRuleEntity", b =>
                {
                    b.HasOne("Dispatch.Data.RelayEntity", null)
                        .WithMany()
                        .HasForeignKey("RelayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
