-- Audit/security event log surfaced on the System Logs page (spec §13/§17). Records who did what
-- (auth, API-key changes, config changes) and unhandled server errors. `kind` is the coarse filter the
-- UI exposes ('audit' vs 'error'); `category`/`severity` add detail. Guarded so the migration re-runs.

CREATE TABLE IF NOT EXISTS audit_log (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logged_at  timestamptz  NOT NULL DEFAULT now(),
    kind       varchar(16)  NOT NULL,                 -- audit | error
    category   varchar(32)  NOT NULL,                 -- Auth | ApiKey | Config | Error
    event      varchar(128) NOT NULL,
    severity   varchar(16)  NOT NULL DEFAULT 'Info',  -- Info | Notice | Warning | Error
    actor      varchar(128) NULL,
    source_ip  varchar(64)  NULL,
    detail     text         NULL
);

-- Default listing order (newest first) + keyset tie-break.
CREATE INDEX IF NOT EXISTS IX_audit_log_at ON audit_log (logged_at DESC, id DESC);
-- The 'audit' vs 'error' filter.
CREATE INDEX IF NOT EXISTS IX_audit_log_kind ON audit_log (kind, logged_at DESC);
