-- Dispatch schema v1 (spec §6.11, §7.6, §12.3). Runs as a single batch;
-- tables are created in FK-dependency order. Guarded by schema_version, so it runs once.

CREATE TABLE config (
    "key"      varchar(128) NOT NULL PRIMARY KEY,
    value      text         NOT NULL,
    encrypted  boolean      NOT NULL DEFAULT false,
    updated_at timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE relays (
    id                int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              varchar(128) NOT NULL UNIQUE,
    provider          varchar(64)  NOT NULL,
    is_default        boolean      NOT NULL DEFAULT false,
    enabled           boolean      NOT NULL DEFAULT true,
    max_concurrency   int          NOT NULL DEFAULT 4,
    max_message_bytes int          NOT NULL DEFAULT 0,
    created_at        timestamptz  NOT NULL DEFAULT now(),
    updated_at        timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IX_relays_default ON relays (is_default) WHERE is_default;

CREATE TABLE routing_rules (
    id                int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority          int          NOT NULL UNIQUE,
    name              varchar(128) NOT NULL,
    recipient_pattern varchar(256) NULL,
    sender_pattern    varchar(256) NULL,
    relay_id          int          NOT NULL REFERENCES relays(id),
    enabled           boolean      NOT NULL DEFAULT true,
    created_at        timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE api_keys (
    id                    int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id                varchar(32)  NOT NULL UNIQUE,
    key_hash              varchar(512) NOT NULL,
    name                  varchar(256) NOT NULL,
    created_at            timestamptz  NOT NULL DEFAULT now(),
    last_used_at          timestamptz  NULL,
    message_count         bigint       NOT NULL DEFAULT 0,
    revoked               boolean      NOT NULL DEFAULT false,
    revoked_at            timestamptz  NULL,
    rate_limit_per_minute int          NOT NULL DEFAULT 100,
    scope                 varchar(64)  NOT NULL DEFAULT 'send'
);
CREATE INDEX IX_api_keys_key_id ON api_keys (key_id) WHERE NOT revoked;

CREATE TABLE relay_counters (
    id        int    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date      date   NOT NULL,
    relay_id  int    NOT NULL REFERENCES relays(id),
    received  bigint NOT NULL DEFAULT 0,
    delivered bigint NOT NULL DEFAULT 0,
    failed    bigint NOT NULL DEFAULT 0,
    retried   bigint NOT NULL DEFAULT 0,
    denied    bigint NOT NULL DEFAULT 0,
    CONSTRAINT UQ_relay_counters UNIQUE (date, relay_id)
);
CREATE INDEX IX_relay_counters_date ON relay_counters (date DESC);

CREATE TABLE relay_log (
    id                  bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logged_at           timestamptz  NOT NULL DEFAULT now(),
    spool_id            varchar(64)  NOT NULL,
    event               varchar(32)  NOT NULL,
    status              varchar(16)  NOT NULL,
    retry_attempt       int          NOT NULL DEFAULT 0,
    from_address        varchar(512) NOT NULL,
    from_domain         varchar(255) NOT NULL,
    to_addresses        text         NOT NULL,
    to_domain           varchar(255) NOT NULL,
    subject             varchar(998) NOT NULL,
    size_bytes          int          NOT NULL DEFAULT 0,
    relay_id            int          NULL REFERENCES relays(id),
    relay_name          varchar(128) NULL,
    routing_rule_id     int          NULL REFERENCES routing_rules(id),
    routing_rule_name   varchar(128) NULL,
    routing_matched     boolean      NOT NULL DEFAULT false,
    provider            varchar(64)  NULL,
    provider_message_id varchar(256) NULL,
    provider_response   text         NULL,
    duration_ms         int          NULL,
    error               text         NULL,
    ingest_source       varchar(16)  NOT NULL DEFAULT 'SMTP',
    source_ip           varchar(64)  NULL,
    api_key_id          int          NULL REFERENCES api_keys(id),
    api_key_name        varchar(256) NULL,
    tags                text         NULL
);
CREATE INDEX IX_relay_log_status_date ON relay_log (status, logged_at DESC)
    INCLUDE (spool_id, from_address, from_domain, to_domain, subject, size_bytes,
             relay_name, routing_rule_name, provider, duration_ms, ingest_source, retry_attempt);
CREATE INDEX IX_relay_log_from_domain ON relay_log (from_domain, logged_at DESC);
CREATE INDEX IX_relay_log_to_domain   ON relay_log (to_domain, logged_at DESC);
CREATE INDEX IX_relay_log_source      ON relay_log (ingest_source, logged_at DESC);
CREATE INDEX IX_relay_log_purge       ON relay_log (logged_at);

CREATE TABLE config_smtp_credentials (
    id            int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(256) NOT NULL UNIQUE,
    password_hash varchar(512) NOT NULL,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    last_used_at  timestamptz  NULL
);

-- Seed a single default relay in the "Unconfigured" state: until an administrator picks a provider,
-- Dispatch refuses to relay (mail is never silently delivered or discarded).
INSERT INTO relays (name, provider, is_default, enabled, max_concurrency)
VALUES ('default', 'Unconfigured', true, true, 4);
